# Generated by Django 4.1.7 on 2023-03-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Reject', 'Отклонено'), ('Accept', 'Принято'), ('In_Consideration', 'В рассмотрении')], default='In_Consideration', max_length=32),
        ),
        migrations.AddField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('Reject', 'Reject'), ('Accept', 'Accept'), ('In_Consideration', 'В рассмотрении')], default='In_Consideration', max_length=32),
        ),
    ]
