# Generated by Django 4.1.7 on 2023-03-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, default='E:\\Projects\\django_digital_store\\digital_store\\static\\img\\default\\shop.jpg', upload_to='shop', verbose_name='Изображение'),
        ),
    ]
