# Generated by Django 4.1.7 on 2023-03-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_image_alter_shop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(blank=True, verbose_name='Количество товара'),
        ),
    ]
