# Generated by Django 4.1.7 on 2023-03-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_shop_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Accept', 'Одобрено'), ('Reject', 'Отклонено'), ('In_Consideration', 'В рассмотрении')], default='In_Consideration', max_length=32),
        ),
    ]
