# Generated by Django 4.1.7 on 2023-03-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='visibile',
            field=models.BooleanField(default=True, verbose_name='Видимость продукта'),
        ),
    ]
