# Generated by Django 4.1.7 on 2023-03-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='shop', verbose_name='Изображение'),
        ),
    ]
