# Generated by Django 4.1.7 on 2023-03-11 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('created_date',)},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ('created_date',)},
        ),
    ]
