# Generated by Django 4.1.7 on 2023-03-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='sluges', max_length=20, unique=True, verbose_name='Уникальный адрес категории'),
            preserve_default=False,
        ),
    ]
