# Generated by Django 4.1.7 on 2023-03-30 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_category_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrowsingHistory',
        ),
    ]
