name: workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
  steps:
  - uses: action/checkout@v2
  - name: Установка Python
    uses: actions/setup-python@v2
    with:
      python-version: 3.7
  - name: Установка зависимостей
    run: |
      python -m pip install --upgrade pip
      pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
      pip install -r django_digital_store/requirements.txt
  - name: Запуск тестов
    run: |
      python -m flake8