# Generated by Django 4.1.7 on 2023-03-06 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0008_product_price_alter_item_product_alter_product_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='shop', verbose_name='Изображение')),
                ('description', models.CharField(max_length=1028, verbose_name='Описание')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('new_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_shop', to='shop.shop', verbose_name='После редактирования')),
            ],
        ),
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('image', models.ImageField(blank=True, upload_to='shop/product_old/', verbose_name='Изображение')),
                ('description', models.CharField(max_length=1024, verbose_name='Описание')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ManyToManyField(related_name='category_before', to='shop.category', verbose_name='Категория')),
                ('new_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_product', to='shop.product', verbose_name='После изменения')),
            ],
        ),
        migrations.CreateModel(
            name='ModerationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('shop', 'Магазин'), ('product', 'Продукт')], max_length=16, verbose_name='Тип')),
                ('reason', models.CharField(max_length=512, verbose_name='Причина')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата проверки')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_in_moderation_history', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_in_moderation_history', to='shop.product', verbose_name='Продукт')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_in_moderation_history', to='shop.shop', verbose_name='Магазин')),
            ],
        ),
    ]
