# Generated by Django 4.1.7 on 2023-03-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationhistory',
            name='reason',
            field=models.CharField(max_length=512, null=True, verbose_name='Причина'),
        ),
    ]
