# Generated by Django 4.1.7 on 2023-03-06 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_price_alter_item_product_alter_product_count_and_more'),
        ('moderation', '0002_alter_moderationhistory_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproduct',
            name='new_product',
        ),
        migrations.RemoveField(
            model_name='newshop',
            name='new_shop',
        ),
        migrations.AddField(
            model_name='newproduct',
            name='old_product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='old_product', to='shop.product', verbose_name='После изменения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newshop',
            name='old_shop',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='old_shop', to='shop.shop', verbose_name='После редактирования'),
            preserve_default=False,
        ),
    ]
