# Generated by Django 4.1.7 on 2023-03-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_remove_newshop_old_shop_delete_newproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationhistory',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последней првоерки'),
        ),
        migrations.AlterField(
            model_name='moderationhistory',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата первой проверки'),
        ),
    ]
