# Generated by Django 4.1.7 on 2023-03-09 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0015_alter_product_image'),
        ('moderation', '0005_moderationhistory_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationhistory',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AlterField(
            model_name='moderationhistory',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation', to='shop.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='moderationhistory',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='shop.shop', verbose_name='Магазин'),
        ),
    ]
