# Generated by Django 4.1.7 on 2023-03-11 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0016_alter_shop_image'),
        ('moderation', '0006_alter_moderationhistory_moderator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptRejectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('shop', 'Магазин'), ('product', 'Продукт')], max_length=16, verbose_name='Тип')),
                ('reason', models.CharField(max_length=512, null=True, verbose_name='Причина')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата последней првоерки')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата первой проверки')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('product', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation', to='shop.product', verbose_name='Продукт')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='shop.shop', verbose_name='Магазин')),
            ],
        ),
        migrations.DeleteModel(
            name='ModerationHistory',
        ),
    ]
