# Generated by Django 4.1.7 on 2023-03-11 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_shop_image'),
        ('moderation', '0007_acceptrejectlist_delete_moderationhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptrejectlist',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='shop.shop', verbose_name='Магазин'),
        ),
    ]
