# Generated by Django 4.1.7 on 2023-03-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0008_alter_acceptrejectlist_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acceptrejectlist',
            options={'verbose_name': 'История модерации', 'verbose_name_plural': 'История модерации'},
        ),
        migrations.AlterField(
            model_name='acceptrejectlist',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последней проверки'),
        ),
    ]
