# Generated by Django 4.1.7 on 2023-03-08 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0014_alter_item_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, verbose_name='Цена за единицу товара')),
                ('full_price', models.FloatField(default=0, verbose_name='Полная цена')),
                ('count_items', models.IntegerField(default=0, verbose_name='Количество')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в корзину')),
                ('items', models.ManyToManyField(related_name='cart', to='shop.item', verbose_name='Товары')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart', to='shop.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
