# Generated by Django 4.1.7 on 2023-03-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_order_order_orderhistory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='count_items',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='full_price',
            field=models.FloatField(default=0, verbose_name='Полная цена'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в корзину'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редактирования'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена за единицу товара'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редактирования'),
        ),
    ]
