# Generated by Django 4.1.7 on 2023-03-11 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_product_options_alter_shop_options'),
        ('cart', '0005_orderhistory_count_items_orderhistory_full_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='shop.product', verbose_name='Продукт'),
        ),
    ]
