# Generated by Django 4.1.7 on 2023-03-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='review',
            field=models.BooleanField(default=False, verbose_name='Отзыв оставлен'),
        ),
    ]
