# Generated by Django 4.1.7 on 2023-03-15 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_orderhistory_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='full_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
