# Generated by Django 4.1.7 on 2023-03-23 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_category_options_alter_item_options_and_more'),
        ('cart', '0009_remove_cart_full_price_remove_cart_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'verbose_name': 'История покупки', 'verbose_name_plural': 'История покупок'},
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_history', to='shop.product', verbose_name='Продукт'),
        ),
    ]
