# Generated by Django 4.1.7 on 2023-03-14 09:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_favorite_favorite_уникальные значения'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
    ]
