# Generated by Django 4.1.7 on 2023-03-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_favorite_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='users/profile_img/', verbose_name='Изображение профиля'),
        ),
    ]
