# Generated by Django 4.1.7 on 2023-03-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='users/profile_img/', verbose_name='Изображение профиля'),
        ),
    ]
